# Generated by Django 4.1.1 on 2023-01-05 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_product_pic1_alter_product_pic2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='pic1',
            new_name='p1',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='pic2',
            new_name='p2',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='pic3',
            new_name='p3',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='pic4',
            new_name='p4',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='pic4',
        ),
        migrations.AddField(
            model_name='buyer',
            name='pic',
            field=models.ImageField(blank=True, default='', null=True, upload_to='uploads'),
        ),
    ]
