# Generated by Django 4.1.1 on 2023-01-05 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_rename_pic1_product_p1_rename_pic2_product_p2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyer',
            old_name='pic',
            new_name='pic4',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='p1',
            new_name='pic1',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='p2',
            new_name='pic2',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='p3',
            new_name='pic3',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='p4',
            new_name='pic4',
        ),
    ]
